# Site settings
title: Adam's Learn Blog
header-img: img/home-bg.png
email: adam.enbar@gmail.com
copyright_name: aenbar
description: > # this means to ignore newlines until "baseurl:"
  Learn. Love. Code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: aenbar
github_username:  aenbar
learn_profile: aenbar
email_username: adam.enbar@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
